server:
  port: 8181

spring:
  application:
    name: product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 1e608fee-5814-4a84-ab9d-35f701d0c625
        group: DEMO_GROUP
      config:
        server-addr: 127.0.0.1:8848
        namespace: 1e608fee-5814-4a84-ab9d-35f701d0c625
        group: DEMO_GROUP
        file-extension: yaml

  config:
    import:
    - optional:nacos:${spring.application.name}-config