server:
  port: 8082

spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 1e608fee-5814-4a84-ab9d-35f701d0c625
        group: DEMO_GROUP
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        namespace: 1e608fee-5814-4a84-ab9d-35f701d0c625
        group: DEMO_GROUP
        username: nacos
        password: nacos
        file-extension: yaml
        shared-configs[0]:
          data-id: share-config
          refresh: true
        extension-configs[0]:
          data-id: extension-config
          refresh: true
  config:
    import:
    - optional:nacos:${spring.application.name}-config