server:
  port: 8081

spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 1e608fee-5814-4a84-ab9d-35f701d0c625
        group: DemoGroup
      config:
        server-addr: 127.0.0.1:8848
        namespace: 1e608fee-5814-4a84-ab9d-35f701d0c625
        group: DemoGroup
        file-extension: yaml
  config:
    import:
    - optional:nacos:${spring.application.name}-config