server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 1e608fee-5814-4a84-ab9d-35f701d0c625
        group: DEMO_GROUP
      config:
        server-addr: 127.0.0.1:8848
        namespace: 1e608fee-5814-4a84-ab9d-35f701d0c625
        group: DEMO_GROUP
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
      enabled: true

  config:
    import:
      - optional:nacos:${spring.application.name}-config